// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5Pai88hZZymPopUWVzxtQ8JOdnPIs9U',
    appId: '1:977282208119:android:be9b791d0907594762d172',
    messagingSenderId: '977282208119',
    projectId: 'vocabricks',
    databaseURL: 'https://vocabricks-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vocabricks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfInqQFjB1UxKavF4pCedy_vBtxKR824',
    appId: '1:977282208119:ios:2b83709a4a8619c262d172',
    messagingSenderId: '977282208119',
    projectId: 'vocabricks',
    databaseURL: 'https://vocabricks-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vocabricks.firebasestorage.app',
    iosBundleId: 'io.github.themihabyte.vocabularybuilder',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZdcL29emalJeTA60vnzxtiHNOYOnQj0',
    appId: '1:977282208119:web:a1d562152e5c935062d172',
    messagingSenderId: '977282208119',
    projectId: 'vocabricks',
    authDomain: 'vocabricks.firebaseapp.com',
    databaseURL: 'https://vocabricks-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'vocabricks.firebasestorage.app',
  );

}